### ISSUE TITLE
Investigate on existing BTC open APIs

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-mobile#564]
There are many companies which develop and maintain BTC tools including wallets. Some of them provide open APIs which we can use to retrieve the account data and make transactions.

This ticket aims to gather a list of these open API providers to help decide which one to use.

**Comment by aydieneue** [comment]
There are several ready to use solutions like [BlockCypher](https://www.blockcypher.com/dev/), [Blockchain](https://www.blockchain.com/api), and [Blockexplorer](https://blockexplorer.com/api-ref). Some of them offer paid plans which increase the rate limit of the API requests. On the other hand, there are also ‘deploy your own node’ kind of solutions provided by projects like [bitcore](https://github.com/bitpay/bitcore) and [bcoin](https://github.com/bcoin-org/bcoin). 

Since we haven’t decided which solution to go for in the production yet, my opinion is to start development with [blockchain](https://www.blockchain.com/api), which provides a good API which includes both blockexplorer (address, transaction lookup) and transaction broadcast endpoints.
