### ISSUE TITLE
Send: Filter state is not empty if bookmark was chosen when going back to initial send screen 

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-mobile#926]
### How to reproduce
1. Create a bookmark
1. Open send screen
1. Click on bookmark
1. Click back button

### Actual behaviour
Filter input filled with bookmark address

### Expected behaviour
Empty filter state

**Comment by RaquelCasadoDias** [comment]
Because of how it is implemented, the input field works also for search of unknown addresses and for filtering bookmarks. The behaviour of going back and having the address on the input field should remain but that means that would also filter the list of bookmarks, which, would display only the bookmark that matches the address. A change from design is needed in order to solve this issue.
